export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=$IGN_GAZEBO_SYSTEM_PLUGIN_PATH:$(pwd)/build/lib
export SDF_PATH=$SDF_PATH:$(pwd)/models
export IGN_FILE_PATH=$IGN_FILE_PATH:$(pwd)/models

echo -e "IGN_GAZEBO_SYSTEM_PLUGIN_PATH $IGN_GAZEBO_SYSTEM_PLUGIN_PATH"
echo -e "SDF_PATH $SDF_PATH"
echo -e "IGN_FILE_PATH $IGN_FILE_PATH"
